"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Activity, ArrowLeft, Bot, Check, CheckCircle2, ChevronRight, CircleAlert, Clock3, Cpu, ExternalLink, HardDrive, KeyRound, Laptop, ListTree, LoaderCircle, MemoryStick, MonitorCog, PackageCheck, Play, Server, ShieldCheck, Wrench } from "lucide-react";
import type { DeviceDetailData } from "@/lib/data";
import type { SessionUser } from "@/lib/rbac";
import { hasReadyRemoteProvider, remoteProviderState, type RemoteProviderState } from "@/lib/remote-provider-state";

const titleCase = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const ago = (value: string | Date) => { const minutes = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 60_000)); return minutes < 1 ? "just now" : minutes < 60 ? `${minutes}m ago` : minutes < 1440 ? `${Math.floor(minutes / 60)}h ago` : `${Math.floor(minutes / 1440)}d ago`; };
const remoteDetails = (value?: string) => { try { return JSON.parse(value || "{}") as { error?: string | null; version?: string | null }; } catch { return {}; } };

function Status({ value }: { value: string }) { return <span className={`status-pill status-${value.replaceAll("_", "-")}`}><i />{titleCase(value)}</span>; }

export function DeviceDetail({ data, user }: { data: DeviceDetailData; user: SessionUser }) {
  const { device } = data;
  const router = useRouter();
  const [tab, setTab] = useState("overview");
  const [busy, setBusy] = useState("");
  const [message, setMessage] = useState("");
  const canAutomate = user.permissionKeys.includes("automation.run");
  const canRemote = user.permissionKeys.includes("remote.control");
  const latestMetric = device.metrics[0];
  const credential = device.agentCredentials[0];
  const refreshAction = data.approvedAutomations.find((automation) => automation.key === "refresh-agent");
  const rustdesk = device.remoteEndpoints.find((endpoint) => endpoint.provider === "rustdesk");
  const rdp = device.remoteEndpoints.find((endpoint) => endpoint.provider === "rdp");
  const rustdeskState = remoteProviderState(rustdesk);
  const rdpState = remoteProviderState(rdp);
  const remoteReady = hasReadyRemoteProvider([rustdesk, rdp]);
  const remotePersistence = remoteReady
    ? "Windows services"
    : rustdeskState === "failed" || rdpState === "failed"
      ? "Provider error"
      : rustdeskState === "stalled" || rdpState === "stalled"
        ? "Retry overdue"
        : "Awaiting agent report";

  async function act(payload: Record<string, unknown>, success: string) {
    setBusy(String(payload.action)); setMessage("");
    const response = await fetch("/api/actions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
    const result = await response.json();
    setBusy(""); setMessage(response.ok ? success : result.error);
    if (response.ok) router.refresh();
  }

  const queue = (automationId: string, name: string) => act({ action: "runAutomation", deviceId: device.id, automationId }, `${name} queued for agent pickup.`);

  return <div className="device-detail">
    <div className="device-breadcrumb"><Link href="/devices"><ArrowLeft size={13} /> Devices</Link><ChevronRight size={12} /><span className="mono">{device.hostname}</span></div>
    <header className="device-hero"><div className="device-hero-main"><span className="device-type-icon">{device.role.includes("Server") ? <Server size={15} /> : <Laptop size={15} />}</span><div className="device-identity"><div className="device-title-line"><h1>{device.displayName}</h1><Status value={device.status} /><span className="live-endpoint-badge"><span /> Agent connected</span></div><dl className="device-identity-facts"><div><dt>Hostname</dt><dd className="mono">{device.hostname}</dd></div><div><dt>Scope</dt><dd>{device.organization.name} / {device.location.name}</dd></div><div><dt>Last contact</dt><dd>{ago(device.lastCheckIn)}</dd></div><div><dt>Agent</dt><dd className="mono">{device.agentVersion}</dd></div></dl></div></div><div className="device-hero-actions">{canRemote ? <Link className="primary-button" href={`/devices/${device.id}/remote`}><MonitorCog size={14} /> Remote control</Link> : <button className="primary-button" disabled title="Your role cannot open remote sessions."><MonitorCog size={14} /> Remote control</button>}<button className="ghost-button" disabled={!canAutomate || !refreshAction || Boolean(busy) || !credential} title={!credential ? "This endpoint has no active agent credential." : undefined} onClick={() => refreshAction && queue(refreshAction.id, refreshAction.name)}>{busy ? <LoaderCircle className="spin" size={14} /> : <Activity size={14} />} Queue refresh</button></div></header>
    {message && <div className={`device-message ${message.toLowerCase().includes("failed") || message.toLowerCase().includes("cannot") ? "error" : ""}`}><CheckCircle2 size={17} />{message}</div>}
    <nav className="detail-tabs" aria-label="Device detail sections">{["overview", "inventory", "monitoring", "patches", "automation", "support", "activity"].map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{titleCase(item)}</button>)}</nav>

    {tab === "overview" && <div className="detail-grid"><section className="panel detail-span-2"><div className="panel-head"><div><h2>Current health</h2><p>Latest authenticated telemetry · checked in {ago(device.lastCheckIn)}</p></div><Activity size={18} /></div><div className="health-gauges"><GaugeCard label="CPU" value={latestMetric?.cpu ?? 0} icon={Cpu} /><GaugeCard label="Memory" value={latestMetric?.memory ?? 0} icon={MemoryStick} /><GaugeCard label="Disk used" value={device.diskUsedPercent} icon={HardDrive} /><div className="health-fact"><Clock3 /><span><small>Uptime</small><strong>{Math.floor(device.uptimeMinutes / 1440)}d {Math.floor((device.uptimeMinutes % 1440) / 60)}h</strong></span></div></div></section><section className="panel"><div className="panel-head"><div><h2>Identity</h2><p>Endpoint and agent details</p></div></div><dl className="fact-list"><div><dt>Operating system</dt><dd>{device.operatingSystem}</dd></div><div><dt>OS version</dt><dd>{device.osVersion}</dd></div><div><dt>Model</dt><dd>{device.manufacturer} {device.model}</dd></div><div><dt>Serial</dt><dd className="mono">{device.serialNumber}</dd></div><div><dt>IP address</dt><dd className="mono">{device.ipAddress}</dd></div><div><dt>Agent</dt><dd>{device.agentVersion}</dd></div></dl></section><section className="panel detail-span-2"><div className="panel-head"><div><h2>Effective policy</h2><p>Resolved inheritance and assignment sources for this endpoint</p></div><ShieldCheck size={18} /></div><div className="policy-precedence">{data.effectivePolicy.precedence.map((item, index) => <span key={`${item.level}-${item.policy}`}><i>{index + 1}</i>{titleCase(item.level)}<strong>{item.policy}</strong>{index < data.effectivePolicy.precedence.length - 1 && <ChevronRight size={14} />}</span>)}</div><div className="effective-settings">{Object.entries(data.effectivePolicy.settings).slice(0, 10).map(([key, value]) => <div key={key}><span><small>{titleCase(key)}</small><strong>{Array.isArray(value) ? value.join(", ") : String(value)}</strong></span><em>{data.effectivePolicy.origins[key]}</em></div>)}</div></section><section className="panel"><div className="panel-head"><div><h2>Open conditions</h2><p>{device.alerts.filter((alert) => alert.status !== "resolved").length} require attention</p></div></div><div className="condition-list">{device.alerts.filter((alert) => alert.status !== "resolved").slice(0, 5).map((alert) => <div key={alert.id}><span className={`severity-icon severity-${alert.severity}`}><CircleAlert size={15} /></span><span><strong>{alert.title}</strong><small>{ago(alert.triggeredAt)} · {alert.ticket ? `Ticket #${alert.ticket.number}` : "No ticket"}</small></span></div>)}{!device.alerts.some((alert) => alert.status !== "resolved") && <div className="healthy-empty"><CheckCircle2 /> No active conditions</div>}</div></section></div>}

    {tab === "inventory" && <div className="detail-grid"><section className="panel"><div className="panel-head"><div><h2>Hardware inventory</h2><p>Collected from the enrolled host</p></div><Cpu size={18} /></div><dl className="fact-list"><div><dt>Processor</dt><dd>{device.cpu}</dd></div><div><dt>Memory</dt><dd>{device.memoryGb} GB</dd></div><div><dt>Storage</dt><dd>{device.diskCapacityGb} GB</dd></div><div><dt>CPU cores</dt><dd>{device.hardwareInventory?.cpuCores ?? "Not reported"}</dd></div><div><dt>BIOS</dt><dd>{device.hardwareInventory?.biosVersion ?? "Not reported"}</dd></div><div><dt>TPM</dt><dd>{device.hardwareInventory?.tpmVersion ?? "Not reported"}</dd></div></dl></section><section className="panel detail-span-2"><div className="panel-head"><div><h2>Software inventory</h2><p>{device.softwareInventory.length} reported applications</p></div><PackageCheck size={18} /></div><div className="inventory-table"><div><span>Application</span><span>Vendor</span><span>Version</span><span>Policy</span></div>{device.softwareInventory.map((software) => <div key={software.id}><strong>{software.name}</strong><span>{software.vendor}</span><span className="mono">{software.version}</span><span>{software.prohibited ? <Status value="prohibited" /> : software.required ? <Status value="required" /> : <span className="muted">Allowed</span>}</span></div>)}</div>{!device.softwareInventory.length && <div className="empty-state compact"><PackageCheck size={21} /><p>No software inventory has been reported.</p></div>}</section></div>}

    {tab === "monitoring" && <div className="detail-grid"><section className="panel detail-span-2"><div className="panel-head"><div><h2>Telemetry history</h2><p>CPU and memory measurements received from this agent</p></div><Activity size={18} /></div><div className="telemetry-chart">{[...device.metrics].reverse().map((metric) => <div key={metric.id}><i style={{ height: `${metric.cpu}%` }} title={`CPU ${metric.cpu}%`} /><b style={{ height: `${metric.memory}%` }} title={`Memory ${metric.memory}%`} /></div>)}</div><div className="legend"><span><i className="legend-cyan" /> CPU</span><span><i className="legend-violet" /> Memory</span></div></section><section className="panel"><div className="panel-head"><div><h2>Agent connection</h2><p>Credential and transport state</p></div><KeyRound size={18} /></div><dl className="fact-list"><div><dt>Management mode</dt><dd>{titleCase(device.managementMode)}</dd></div><div><dt>Credential</dt><dd className="mono">{credential ? `${credential.secretPrefix}…` : "No active credential"}</dd></div><div><dt>Credential issued</dt><dd>{credential ? ago(credential.createdAt) : "—"}</dd></div><div><dt>Last authenticated use</dt><dd>{credential?.lastUsedAt ? ago(credential.lastUsedAt) : "Not used yet"}</dd></div><div><dt>Transport</dt><dd>HTTPS polling</dd></div></dl></section></div>}

    {tab === "patches" && <section className="panel"><div className="panel-head"><div><h2>Applicable patches</h2><p>{device.patchCompliance}% compliant · {device.pendingReboot ? "Reboot pending" : "No reboot pending"}</p></div><PackageCheck size={18} /></div><div className="inventory-table patch-detail-table"><div><span>Patch</span><span>Severity</span><span>Approval</span><span>Device state</span></div>{device.patchStates.map((state) => <div key={state.id}><span><strong>{state.patch.title}</strong><small>{state.patch.identifier}</small></span><Status value={state.patch.severity} /><Status value={state.patch.approvalState} /><span><Status value={state.state} />{state.failureReason && <small className="failure-text">{state.failureReason}</small>}</span></div>)}</div>{!device.patchStates.length && <div className="empty-state"><PackageCheck size={24} /><h3>No patch inventory reported</h3><p>Patch execution is not enabled for this agent.</p></div>}</section>}

    {tab === "automation" && <div className="detail-grid"><section className="panel detail-span-2"><div className="panel-head"><div><h2>Approved agent actions</h2><p>Only allowlisted refresh tasks are available; there is no arbitrary command execution.</p></div><Bot size={18} /></div><div className="device-automation-list">{data.approvedAutomations.map((automation) => <div key={automation.id}><span className="policy-icon"><Wrench size={16} /></span><span><strong>{automation.name}</strong><small>{automation.description}</small></span><button className="small-button" disabled={!canAutomate || Boolean(busy) || !credential} title={!credential ? "This endpoint has no active agent credential." : !canAutomate ? "Your role cannot run automation." : undefined} onClick={() => queue(automation.id, automation.name)}><Play size={14} /> Queue</button></div>)}</div></section><section className="panel"><div className="panel-head"><div><h2>Execution history</h2><p>Latest tasks for this endpoint</p></div></div><div className="run-feed">{device.automationRuns.map((run) => <div className="run-item" key={run.id}><span className={`run-result ${run.status}`}>{run.status === "succeeded" ? <Check size={14} /> : run.status === "queued" || run.status === "running" ? <Clock3 size={14} /> : <CircleAlert size={14} />}</span><span><strong>{run.automation.name}</strong><small>{run.requestedBy.name} · {run.triggerSource}</small></span><time>{ago(run.createdAt)}</time></div>)}</div></section></div>}

    {tab === "support" && <div className="detail-grid"><section className="panel detail-span-2"><div className="panel-head"><div><h2>Remote support providers</h2><p>RustDesk is primary; Windows RDP is the LAN fallback</p></div><MonitorCog size={18} /></div><div className="remote-provider-list"><RemoteProvider name="RustDesk" role="Primary · native client" endpoint={rustdesk} action={canRemote ? <Link className={rustdeskState === "ready" ? "primary-button" : "ghost-button"} href={`/devices/${device.id}/remote`}>{rustdeskState === "ready" ? <ExternalLink size={14} /> : <MonitorCog size={14} />} {rustdeskState === "ready" ? "Open primary" : "View details"}</Link> : undefined} /><RemoteProvider name="Windows RDP" role="Secondary · NLA profile" endpoint={rdp} action={canRemote ? <Link className="ghost-button" href={`/devices/${device.id}/remote`}><MonitorCog size={14} /> {rdpState === "ready" ? "Open fallback" : "View details"}</Link> : undefined} /></div></section><section className="panel"><div className="panel-head"><div><h2>Connection facts</h2><p>Reported agent and provider state</p></div></div><dl className="fact-list"><div><dt>Last check-in</dt><dd>{ago(device.lastCheckIn)}</dd></div><div><dt>Agent version</dt><dd>{device.agentVersion}</dd></div><div><dt>OpsPilot mode</dt><dd>Tray monitor</dd></div><div><dt>Remote persistence</dt><dd>{remotePersistence}</dd></div><div><dt>Remote permission</dt><dd>{canRemote ? "Granted" : "Not granted"}</dd></div></dl></section></div>}

    {tab === "activity" && <section className="panel"><div className="panel-head"><div><h2>Device activity</h2><p>Condition, action, telemetry, and patch history</p></div><ListTree size={18} /></div><div className="timeline">{[...device.alerts.map((alert) => ({ id: alert.id, time: alert.triggeredAt, title: alert.title, detail: `Alert ${alert.status}`, icon: CircleAlert })), ...device.automationRuns.map((run) => ({ id: run.id, time: run.createdAt, title: run.automation.name, detail: `Agent task ${run.status} · ${run.requestedBy.name}`, icon: Bot })), ...device.agentSessions.map((session) => ({ id: session.id, time: session.startedAt, title: `${titleCase(session.type)} check-in`, detail: `${titleCase(session.status)} · authenticated agent`, icon: Activity }))].sort((a, b) => new Date(b.time).getTime() - new Date(a.time).getTime()).slice(0, 30).map((event) => <div key={`${event.id}-${event.title}`}><span><event.icon size={15} /></span><div><strong>{event.title}</strong><p>{event.detail}</p></div><time>{ago(event.time)}</time></div>)}</div></section>}
  </div>;
}

function GaugeCard({ label, value, icon: Icon }: { label: string; value: number; icon: typeof Activity }) {
  return <div className="gauge-card"><span><Icon size={17} />{label}</span><strong>{Math.round(value)}%</strong><div><i style={{ width: `${Math.min(100, value)}%` }} /></div><small>{value > 85 ? "Above policy target" : "Within expected range"}</small></div>;
}

function RemoteProvider({ name, role, endpoint, action }: { name: string; role: string; endpoint?: { externalId: string; status: string; serverUrl: string; details: string; lastVerifiedAt: string | Date | null }; action?: React.ReactNode }) {
  const details = remoteDetails(endpoint?.details);
  const state = remoteProviderState(endpoint);
  return <div className="remote-provider-row"><span className="remote-provider-icon"><MonitorCog size={15} /></span><span className="remote-provider-main"><strong>{name}</strong><small>{role}</small>{state === "failed" && details.error && <em>{details.error}</em>}</span><span className="remote-provider-facts"><span className="mono">{endpoint?.externalId || "Awaiting agent"}</span><small>{endpoint?.lastVerifiedAt ? `Reported ${ago(endpoint.lastVerifiedAt)}` : endpoint?.serverUrl || "No provider report"}{details.version ? ` · v${details.version}` : ""}</small></span><Status value={state} />{action || <button className="ghost-button" disabled>{remoteActionLabel(state)}</button>}</div>;
}

function remoteActionLabel(state: RemoteProviderState) {
  if (state === "failed") return "Unavailable";
  if (state === "stalled") return "Retry overdue";
  if (state === "awaiting-agent") return "Awaiting report";
  return state === "provisioning" ? "Provisioning" : "Not permitted";
}
