"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Activity, ArrowLeft, Bot, Check, CheckCircle2, ChevronRight, CircleAlert, Clock3, Cpu, Folder, HardDrive, Laptop, ListTree, LoaderCircle, MemoryStick, MonitorCog, PackageCheck, Play, Server, ShieldCheck, SquareTerminal, StopCircle, UserCheck, Wrench } from "lucide-react";
import type { DeviceDetailData } from "@/lib/data";
import type { SessionUser } from "@/lib/rbac";

const titleCase = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const ago = (value: string | Date) => { const minutes = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 60_000)); return minutes < 60 ? `${Math.max(1, minutes)}m ago` : minutes < 1440 ? `${Math.floor(minutes / 60)}h ago` : `${Math.floor(minutes / 1440)}d ago`; };

function Status({ value }: { value: string }) { return <span className={`status-pill status-${value.replaceAll("_", "-")}`}><i />{titleCase(value)}</span>; }

export function DeviceDetail({ data, user }: { data: DeviceDetailData; user: SessionUser }) {
  const { device } = data;
  const router = useRouter();
  const [tab, setTab] = useState("overview");
  const [busy, setBusy] = useState("");
  const [message, setMessage] = useState("");
  const canOperate = user.permissionKeys.includes("device.manage");
  const canAutomate = user.permissionKeys.includes("automation.run");
  const fields = JSON.parse(device.customFields || "{}");
  const latestMetric = device.metrics[0];

  async function act(payload: Record<string, unknown>, success: string) {
    setBusy(String(payload.action)); setMessage("");
    const response = await fetch("/api/actions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
    const result = await response.json();
    setBusy(""); setMessage(response.ok ? success : result.error);
    if (response.ok) router.refresh();
  }
  const activeDiagnostic = device.agentSessions.find((session) => session.type === "diagnostic" && session.status === "active");

  return <div className="device-detail">
    <div className="device-breadcrumb"><Link href="/devices"><ArrowLeft size={15} /> Devices</Link><ChevronRight size={14} /><span>{device.hostname}</span></div>
    <header className="device-hero"><div className="device-hero-main"><span className="device-large-icon">{device.role.includes("Server") ? <Server size={28} /> : <Laptop size={28} />}</span><div><div className="device-title-line"><h1>{device.displayName}</h1><Status value={device.status} /><span className="sim-badge"><span /> SIMULATED ENDPOINT</span></div><p><span className="mono">{device.hostname}</span> · {device.organization.name} / {device.location.name}</p></div></div><div className="device-hero-actions"><button className="ghost-button" disabled={!canOperate || Boolean(busy)} title={!canOperate ? "Your role cannot change simulator state." : undefined} onClick={() => act({ action: "setSimulator", deviceId: device.id, state: device.simulatorState === "running" ? "stopped" : "running" }, `Simulator ${device.simulatorState === "running" ? "stopped" : "started"}.`)}>{device.simulatorState === "running" ? <StopCircle size={16} /> : <Play size={16} />}{device.simulatorState === "running" ? "Stop agent" : "Start agent"}</button><button className="primary-button" disabled={!canOperate || Boolean(busy)} onClick={() => act({ action: "requestSession", deviceId: device.id, approvedBy: "Demo User" }, "Simulated diagnostic session started.")}><MonitorCog size={16} /> Request diagnostics</button></div></header>
    {message && <div className={`device-message ${message.includes("cannot") || message.includes("failed") ? "error" : ""}`}>{busy ? <LoaderCircle className="spin" /> : <CheckCircle2 size={17} />}{message}</div>}
    <nav className="detail-tabs" aria-label="Device detail sections">{["overview", "inventory", "monitoring", "patches", "automation", "support", "activity"].map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{titleCase(item)}</button>)}</nav>

    {tab === "overview" && <div className="detail-grid"><section className="panel detail-span-2"><div className="panel-head"><div><h2>Current health</h2><p>Latest simulator telemetry · checked in {ago(device.lastCheckIn)}</p></div><Activity size={18} /></div><div className="health-gauges"><GaugeCard label="CPU" value={latestMetric?.cpu ?? 0} icon={Cpu} /><GaugeCard label="Memory" value={latestMetric?.memory ?? 0} icon={MemoryStick} /><GaugeCard label="Disk used" value={device.diskUsedPercent} icon={HardDrive} /><div className="health-fact"><Clock3 /><span><small>Uptime</small><strong>{Math.floor(device.uptimeMinutes / 1440)}d {Math.floor((device.uptimeMinutes % 1440) / 60)}h</strong></span></div></div></section><section className="panel"><div className="panel-head"><div><h2>Identity</h2><p>Endpoint and agent details</p></div></div><dl className="fact-list"><div><dt>Operating system</dt><dd>{device.operatingSystem}</dd></div><div><dt>OS version</dt><dd>{device.osVersion}</dd></div><div><dt>Model</dt><dd>{device.manufacturer} {device.model}</dd></div><div><dt>Serial</dt><dd className="mono">{device.serialNumber}</dd></div><div><dt>IP address</dt><dd className="mono">{device.ipAddress}</dd></div><div><dt>Agent</dt><dd>{device.agentVersion}</dd></div></dl></section><section className="panel detail-span-2"><div className="panel-head"><div><h2>Effective policy</h2><p>Resolved inheritance and assignment sources for this endpoint</p></div><ShieldCheck size={18} /></div><div className="policy-precedence">{data.effectivePolicy.precedence.map((item, index) => <span key={`${item.level}-${item.policy}`}><i>{index + 1}</i>{titleCase(item.level)}<strong>{item.policy}</strong>{index < data.effectivePolicy.precedence.length - 1 && <ChevronRight size={14} />}</span>)}</div><div className="effective-settings">{Object.entries(data.effectivePolicy.settings).slice(0, 10).map(([key, value]) => <div key={key}><span><small>{titleCase(key)}</small><strong>{Array.isArray(value) ? value.join(", ") : String(value)}</strong></span><em>{data.effectivePolicy.origins[key]}</em></div>)}</div></section><section className="panel"><div className="panel-head"><div><h2>Open conditions</h2><p>{device.alerts.filter((alert) => alert.status !== "resolved").length} require attention</p></div></div><div className="condition-list">{device.alerts.filter((alert) => alert.status !== "resolved").slice(0, 5).map((alert) => <div key={alert.id}><span className={`severity-icon severity-${alert.severity}`}><CircleAlert size={15} /></span><span><strong>{alert.title}</strong><small>{ago(alert.triggeredAt)} · {alert.ticket ? `Ticket #${alert.ticket.number}` : "No ticket"}</small></span></div>)}{!device.alerts.some((alert) => alert.status !== "resolved") && <div className="healthy-empty"><CheckCircle2 /> No active conditions</div>}</div></section></div>}

    {tab === "inventory" && <div className="detail-grid"><section className="panel"><div className="panel-head"><div><h2>Hardware inventory</h2><p>Collected by simulated agent</p></div><Cpu size={18} /></div><dl className="fact-list"><div><dt>Processor</dt><dd>{device.cpu}</dd></div><div><dt>Memory</dt><dd>{device.memoryGb} GB</dd></div><div><dt>Storage</dt><dd>{device.diskCapacityGb} GB</dd></div><div><dt>CPU cores</dt><dd>{device.hardwareInventory?.cpuCores}</dd></div><div><dt>BIOS</dt><dd>{device.hardwareInventory?.biosVersion}</dd></div><div><dt>TPM</dt><dd>{device.hardwareInventory?.tpmVersion ?? "Not reported"}</dd></div></dl></section><section className="panel detail-span-2"><div className="panel-head"><div><h2>Software inventory</h2><p>{device.softwareInventory.length} discovered applications</p></div><PackageCheck size={18} /></div><div className="inventory-table"><div><span>Application</span><span>Vendor</span><span>Version</span><span>Policy</span></div>{device.softwareInventory.map((software) => <div key={software.id}><strong>{software.name}</strong><span>{software.vendor}</span><span className="mono">{software.version}</span><span>{software.prohibited ? <Status value="prohibited" /> : software.required ? <Status value="required" /> : <span className="muted">Allowed</span>}</span></div>)}</div></section></div>}

    {tab === "monitoring" && <div className="detail-grid"><section className="panel detail-span-3"><div className="panel-head"><div><h2>Telemetry history</h2><p>Recent CPU and memory measurements from the simulator</p></div><Activity size={18} /></div><div className="telemetry-chart">{[...device.metrics].reverse().map((metric) => <div key={metric.id}><i style={{ height: `${metric.cpu}%` }} title={`CPU ${metric.cpu}%`} /><b style={{ height: `${metric.memory}%` }} title={`Memory ${metric.memory}%`} /></div>)}</div><div className="legend"><span><i className="legend-cyan" /> CPU</span><span><i className="legend-violet" /> Memory</span></div></section><section className="panel detail-span-3"><div className="panel-head"><div><h2>Condition lab</h2><p>Trigger safe test conditions to validate detection and remediation.</p></div><SquareTerminal size={18} /></div><div className="condition-actions">{[["service_stopped", "Stopped service"], ["missing_patch", "Missing critical patch"], ["pending_reboot", "Pending reboot"], ["prohibited_software", "Prohibited software"], ["offline", "Offline agent"]].map(([condition, label]) => <button key={condition} className="ghost-button" disabled={!canOperate || Boolean(busy)} title={!canOperate ? "Your role cannot change simulator conditions." : undefined} onClick={() => act({ action: "simulateCondition", deviceId: device.id, condition }, `${label} condition triggered. Alert and ticket workflows evaluated.`)}><CircleAlert size={15} />{label}</button>)}</div></section></div>}

    {tab === "patches" && <section className="panel"><div className="panel-head"><div><h2>Applicable patches</h2><p>{device.patchCompliance}% compliant · {device.pendingReboot ? "Reboot pending" : "No reboot pending"}</p></div><PackageCheck size={18} /></div><div className="inventory-table patch-detail-table"><div><span>Patch</span><span>Severity</span><span>Approval</span><span>Device state</span></div>{device.patchStates.map((state) => <div key={state.id}><span><strong>{state.patch.title}</strong><small>{state.patch.identifier}</small></span><Status value={state.patch.severity} /><Status value={state.patch.approvalState} /><span><Status value={state.state} />{state.failureReason && <small className="failure-text">{state.failureReason}</small>}</span></div>)}</div></section>}

    {tab === "automation" && <div className="detail-grid"><section className="panel detail-span-2"><div className="panel-head"><div><h2>Approved actions</h2><p>No arbitrary command execution is available.</p></div><Bot size={18} /></div><div className="device-automation-list">{data.approvedAutomations.map((automation) => <div key={automation.id}><span className="policy-icon"><Wrench size={16} /></span><span><strong>{automation.name}</strong><small>{automation.description}</small></span><button className="small-button" disabled={!canAutomate || Boolean(busy)} title={!canAutomate ? "Your role cannot run automation." : undefined} onClick={() => act({ action: "runAutomation", deviceId: device.id, automationId: automation.id, confirmed: automation.riskLevel === "medium" }, `${automation.name} completed in the simulator.`)}><Play size={14} /> Run</button></div>)}</div></section><section className="panel"><div className="panel-head"><div><h2>Execution history</h2><p>Latest runs for this endpoint</p></div></div><div className="run-feed">{device.automationRuns.map((run) => <div className="run-item" key={run.id}><span className={`run-result ${run.status}`}>{run.status === "succeeded" ? <Check size={14} /> : <CircleAlert size={14} />}</span><span><strong>{run.automation.name}</strong><small>{run.requestedBy.name} · {run.triggerSource}</small></span><time>{ago(run.createdAt)}</time></div>)}</div></section></div>}

    {tab === "support" && <div className="detail-grid"><section className="panel detail-span-2"><div className="panel-head"><div><h2>Simulated diagnostic session</h2><p>Safe, read-only demonstration telemetry with explicit user approval.</p></div><MonitorCog size={18} /></div>{activeDiagnostic ? <div className="active-session"><span className="pulse-ring"><i /></span><div><strong>Diagnostic session active</strong><p>Requested by {activeDiagnostic.requestedBy} · approved by {activeDiagnostic.approvedBy}</p></div><button className="danger-button" disabled={!canOperate} onClick={() => act({ action: "endSession", sessionId: activeDiagnostic.id }, "Simulated diagnostic session ended.")}><StopCircle size={15} /> End session</button></div> : <div className="session-empty"><UserCheck size={28} /><h3>No active session</h3><p>A support session never appears connected unless its simulated approval record exists.</p><button className="primary-button" disabled={!canOperate} onClick={() => act({ action: "requestSession", deviceId: device.id, approvedBy: "Demo User" }, "Simulated diagnostic session started.")}><Play size={15} /> Request user-approved session</button></div>}<div className="diagnostic-panels"><div><h3>Processes</h3>{[["system", "1.2%"], ["ops-agent", "0.8%"], ["browser", "6.4%"]].map((item) => <p key={item[0]}><span>{item[0]}</span><b>{item[1]} CPU</b></p>)}</div><div><h3>Services</h3>{[["OpsPilot Agent", "running"], ["Print Spooler", fields.serviceState ?? "running"], ["Update Service", "running"]].map((item) => <p key={item[0]}><span>{item[0]}</span><Status value={item[1]} /></p>)}</div><div><h3>File inventory</h3>{["C:\\Program Files", "C:\\Users", "C:\\Windows\\Logs"].map((path) => <p key={path}><Folder size={14} /><span className="mono">{path}</span></p>)}</div></div></section><section className="panel"><div className="panel-head"><div><h2>Session history</h2><p>Requester, approval, and end state</p></div></div><div className="session-history">{device.agentSessions.filter((session) => session.type === "diagnostic").map((session) => <div key={session.id}><span><strong>{titleCase(session.status)}</strong><small>{session.requestedBy ?? "System"} · {ago(session.startedAt)}</small></span><Status value={session.simulatorOnly ? "simulated" : "live"} /></div>)}</div></section></div>}

    {tab === "activity" && <section className="panel"><div className="panel-head"><div><h2>Device activity</h2><p>Condition, action, session, and patch history</p></div><ListTree size={18} /></div><div className="timeline">{[...device.alerts.map((alert) => ({ id: alert.id, time: alert.triggeredAt, title: alert.title, detail: `Alert ${alert.status}`, icon: CircleAlert })), ...device.automationRuns.map((run) => ({ id: run.id, time: run.createdAt, title: run.automation.name, detail: `Automation ${run.status} · ${run.requestedBy.name}`, icon: Bot })), ...device.agentSessions.map((session) => ({ id: session.id, time: session.startedAt, title: `${titleCase(session.type)} session`, detail: `${titleCase(session.status)} · simulator-only`, icon: MonitorCog }))].sort((a, b) => new Date(b.time).getTime() - new Date(a.time).getTime()).slice(0, 30).map((event) => <div key={`${event.id}-${event.title}`}><span><event.icon size={15} /></span><div><strong>{event.title}</strong><p>{event.detail}</p></div><time>{ago(event.time)}</time></div>)}</div></section>}
  </div>;
}

function GaugeCard({ label, value, icon: Icon }: { label: string; value: number; icon: typeof Activity }) {
  return <div className="gauge-card"><span><Icon size={17} />{label}</span><strong>{Math.round(value)}%</strong><div><i style={{ width: `${Math.min(100, value)}%` }} /></div><small>{value > 85 ? "Above policy target" : "Within expected range"}</small></div>;
}
